name: CI

on:
  push:
    branches:
        - main
  
  pull_request:
    branches:
        - main
        
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        
  Test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: Select Xcode
        run: sudo xcode-select -switch
            /Applications/Xcode_11.3.app &&
            /usr/bin/xcodebuild -version
      - name: Run unit tests
        run: xcodebuild clean test -project 'GithubAction/GithubAction.xcodeproj' -scheme 'GithubAction' -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest'
            | xcpretty && exit ${PIPESTATUS[0]}


